version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: master
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
