ci:
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: check-json
  - id: check-yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/glotzerlab/fix-license-header
  rev: 43eb3ff2d02cba5e572f86af5c15337823fb2c66
  hooks:
  - id: fix-license-header
    name: Fix license headers (Python)
    types_or: [python, cython]
    args:
    - --license-file=LICENSE
    - --add=Part of fresnel, released under the BSD 3-Clause License.
    - --keep-before=#!
  - id: fix-license-header
    name: Fix license headers (C)
    types_or: [c, c++, cuda, inc]
    args:
    - --license-file=LICENSE
    - --add=Part of fresnel, released under the BSD 3-Clause License.
    - --comment-prefix=//
  - id: fix-license-header
    name: Fix license headers (reStructuredText)
    types_or: [rst]
    args:
    - --license-file=LICENSE
    - --add=Part of fresnel, released under the BSD 3-Clause License.
    - --keep-after=.. include
    - --comment-prefix=..
- repo: https://github.com/google/yapf
  rev: 'v0.32.0'
  hooks:
  - id: yapf
- repo: https://github.com/PyCQA/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8
    additional_dependencies:
    - pep8-naming
    - flake8-docstrings
    - flake8-rst-docstrings
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v15.0.6
  hooks:
  - id: clang-format
    types_or: [c, c++, cuda, inc]
    exclude: (?:^extern/)
