repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.4.0'
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: check-json
  - id: check-yaml
  - id: check-case-conflict
- repo: https://github.com/google/yapf
  rev: 'v0.31.0'
  hooks:
  - id: yapf
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.1'
  hooks:
  - id: flake8
    args:
    - --show-source
    additional_dependencies:
    - pep8-naming
    - flake8-docstrings
    - flake8-rst-docstrings
- repo: https://github.com/glotzerlab/pre-commit-clang-format
  rev: v1.0.0
  hooks:
  - id: clang-format
    stages: [manual]
    exclude: (?:^extern/)
