ci:
  autoupdate_schedule: quarterly
  skip: [clang-format]

repos:
- repo: local
  hooks:
  - id: make_workflows
    name: make_workflows
    language: python
    entry: python3 .github/workflows/make_workflows.py
    pass_filenames: false
    always_run: true
    additional_dependencies: [jinja2==2.11.3, pyyaml==5.4.1]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.1.0'
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: check-json
  - id: check-yaml
    exclude: (?:^.github/workflows/templates) # templates are not properly formatted yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/glotzerlab/fix-license-header
  rev: 686eea86f3a812bf1227a9d074c8328a459c5a66
  hooks:
  - id: fix-license-header
    name: Fix license headers (Python)
    types_or: [python, cython]
    args:
    - --license-file=LICENSE
    - --add=Part of fresnel, released under the BSD 3-Clause License.
    - --keep-before=#!
  - id: fix-license-header
    name: Fix license headers (C)
    types_or: [c, c++, cuda, inc]
    args:
    - --license-file=LICENSE
    - --add=Part of fresnel, released under the BSD 3-Clause License.
    - --comment-prefix=//
  - id: fix-license-header
    name: Fix license headers (reStructuredText)
    types_or: [rst]
    args:
    - --license-file=LICENSE
    - --add=Part of fresnel, released under the BSD 3-Clause License.
    - --keep-after=.. include
    - --comment-prefix=..
- repo: https://github.com/google/yapf
  rev: 'v0.32.0'
  hooks:
  - id: yapf
- repo: https://github.com/PyCQA/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    additional_dependencies:
    - pep8-naming
    - flake8-docstrings
    - flake8-rst-docstrings
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.0
  hooks:
  - id: clang-format
    types_or: [c, c++, cuda, inc]
    exclude: (?:^extern/)
