[workspace]
authors = ["Joshua A. Anderson <joaander@umich.edu>"]
channels = ["conda-forge"]
name = "fresnel"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
conda = "*"
conda-lock = "*"
bump2version = "*"
