pipeline
    {
    options { skipDefaultCheckout() }
    agent none

    stages
        {
        stage('Unit and validation tests')
            {
            when { not { branch 'release' } }

            parallel
                {
                stage('cuda9-optix51')
                    {
                    agent { label 'gpu-short' }

                    environment
                        {
                        CC = 'gcc'
                        CXX = 'g++'
                        CONTAINER = '/nfs/turbo/glotzer/containers/ci/ci-2019.05-cuda9-optix51.simg'
                        }

                    steps
                        {
                        sh 'echo ${NODE_NAME}'

                        dir('code')
                            {
                            checkout scm
                            sh 'git submodule update --init'
                            }

                        dir('build')
                            {
                            timeout(time: 1, unit: 'HOURS')
                                {
                                sh '''
                                    singularity exec --nv ${CONTAINER} cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_EMBREE=OFF -DENABLE_OPTIX=ON -GNinja
                                   '''

                                sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                                }
                            }

                        dir('code/test')
                            {
                            timeout(time: 2, unit: 'HOURS')
                                {
                                sh '''
                                    export PYTHONPATH=${WORKSPACE}/build
                                    singularity exec --nv ${CONTAINER} /usr/bin/python3.6 -m pytest --junit-xml=${WORKSPACE}/test.xml
                                   '''
                                }
                            }

                        junit 'test.xml'
                        }
                    post
                        {
                        always
                            {
                            archive 'test.xml'
                            deleteDir()
                            }
                        }
                    }
                stage('cuda10-optix51')
                    {
                    agent { label 'gpu-short' }

                    environment
                        {
                        CC = 'gcc'
                        CXX = 'g++'
                        CONTAINER = '/nfs/turbo/glotzer/containers/ci/ci-2019.05-cuda10-optix51.simg'
                        }

                    steps
                        {
                        sh 'echo ${NODE_NAME}'

                        dir('code')
                            {
                            checkout scm
                            sh 'git submodule update --init'
                            }

                        dir('build')
                            {
                            timeout(time: 1, unit: 'HOURS')
                                {
                                sh '''
                                    singularity exec --nv ${CONTAINER} cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_EMBREE=OFF -DENABLE_OPTIX=ON -GNinja
                                   '''

                                sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                                }
                            }

                        dir('code/test')
                            {
                            timeout(time: 2, unit: 'HOURS')
                                {
                                sh '''
                                    export PYTHONPATH=${WORKSPACE}/build
                                    singularity exec --nv ${CONTAINER} /usr/bin/python3.6 -m pytest --junit-xml=${WORKSPACE}/test.xml
                                   '''
                                }
                            }

                        junit 'test.xml'
                        }
                    post
                        {
                        always
                            {
                            archive 'test.xml'
                            deleteDir()
                            }
                        }
                    }
                
                }
            }
        }
    }
