pipeline
    {
    options { skipDefaultCheckout() }
    agent none

    stages
        {
        stage('Unit and validation tests')
            {
            when { not { branch 'release' } }
            failFast true
            parallel
                {
                stage('gcc6-py36-cd90-optx50')
                    {
                    agent { label 'gpu' }

                    environment
                        {
                        CC = '/usr/sbin/gcc-6'
                        CXX = '/usr/sbin/g++-6'
                        PYVER = '3.6'
                        PYTEST = '/usr/bin/pytest'
                        CMAKE_BIN = '/usr/sbin'
                        ENABLE_OPTIX = 'ON'
                        CONTAINER = '/nfs/glotzer/containers/ci-optix-2018.02.simg'
                        }

                    steps
                        {
                        sh 'echo ${NODE_NAME}'

                        dir('code')
                            {
                            checkout scm
                            sh 'git submodule update --init'
                            }

                        dir('build')
                            {
                            timeout(time: 1, unit: 'HOURS')
                                {
                                sh '''
                                    singularity exec --nv ${CONTAINER} ${CMAKE_BIN}/cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python${PYVER} -DENABLE_CUDA=${ENABLE_OPTIX} -DENABLE_OPTIX=${ENABLE_OPTIX} -GNinja
                                   '''

                                sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                                }
                            }

                        dir('code/test')
                            {
                            timeout(time: 2, unit: 'HOURS')
                                {
                                sh '''
                                    singularity exec --nv ${CONTAINER} ${PYTEST} --junit-xml=${WORKSPACE}/test.xml
                                   '''
                                }
                            }

                        junit 'test.xml'
                        }
                    post
                        {
                        always
                            {
                            archive 'test.xml'
                            deleteDir()
                            }
                        }
                    }
                
                }
            }

        stage('conda-build-mac')
            {
            agent { label 'mac' }

            environment
                {
                CONDA_BLD_PATH = "${WORKSPACE}/conda-bld"
                ANACONDA_TOKEN = credentials('glotzer-anaconda-token')
                }

            steps
                {
                sh 'echo ${CONDA_BLD_PATH}'

                retry(5)
                    {
                    dir('code')
                        {
                        checkout scm

                        timeout(time: 2, unit: 'HOURS')
                            {
                            sh 'git submodule update --init'

                            sh '''
                               conda build conda-recipe
                               '''
                            }
                        }
                    }

                script
                    {
                    if (env.BRANCH_NAME == 'release')
                        {
                        sh 'anaconda -t ${ANACONDA_TOKEN} upload --force --no-progress ${WORKSPACE}/conda-bld/**/*.tar.bz2'
                        }
                    }
                }
            post
                {
                always
                    {
                    deleteDir()
                    }
                }
            }
        }
    }
