pipeline
    {
    options { skipDefaultCheckout() }
    agent none

    stages
        {
        stage('Unit and validation tests')
            {
            when { not { branch 'release' } }
            failFast true
            parallel
                {
                stage('cuda9-optix50')
                    {
                    agent { label 'gpu' }

                    environment
                        {
                        CC = 'gcc'
                        CXX = 'g++'
                        CONTAINER = '/nfs/glotzer/containers/ci-optix-2018.05.simg'
                        }

                    steps
                        {
                        sh 'echo ${NODE_NAME}'

                        dir('code')
                            {
                            checkout scm
                            sh 'git submodule update --init'
                            }

                        dir('build')
                            {
                            timeout(time: 1, unit: 'HOURS')
                                {
                                sh '''
                                    singularity exec --nv ${CONTAINER} cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_CUDA=ON -DENABLE_EMBREE=OFF -DENABLE_TBB=OFF -DENABLE_OPTIX=ON -GNinja
                                   '''

                                sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                                }
                            }

                        dir('code/test')
                            {
                            timeout(time: 2, unit: 'HOURS')
                                {
                                sh '''
                                    export PYTHONPATH=${WORKSPACE}/build
                                    singularity exec --nv ${CONTAINER} py.test-3 --junit-xml=${WORKSPACE}/test.xml
                                   '''
                                }
                            }

                        junit 'test.xml'
                        }
                    post
                        {
                        always
                            {
                            archive 'test.xml'
                            deleteDir()
                            }
                        }
                    }
                
                }
            }
        }
    }
