name: Unit test

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches and version tags. This prevents building commits
  # twice when the pull request source branch is in the same repository.
  push:
    branches:
      - "master"

  # Trigger on request.
  workflow_dispatch:

jobs:
  unit_test_linux:
    name: Unit test on Linux [${{ matrix.image }}]
    runs-on: ubuntu-latest
    container:
      image: glotzerlab/ci:2021.04-${{ matrix.image }}
      options: -u 0
    strategy:
      matrix:
        include:
          - image: clang11_py39
            render_gallery: true
          - image: gcc10_py39


                # gcc9_py38,
                # clang10_py38,
                # clang9_py38,
                # clang8_py38,
                # clang7_py38,
                # gcc8_py37,
                # gcc7_py37,
                # clang6_py37,
                # gcc7_py36,

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          path: code
          submodules: true
      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake ../code -GNinja \
                        -DENABLE_EMBREE=${ENABLE_EMBREE:-"ON"} \
                        -DENABLE_OPTIX=${ENABLE_OPTIX:-"OFF"} \
                        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
        env:
          ENABLE_OPTIX: ${{ matrix.enable_optix }}
          ENABLE_EMBREE: ${{ matrix.enable_embree }}
      - name: Build
        run: ninja install
        working-directory: build
      - run: ls ${{ github.workspace }}/install/fresnel
      - run: python3 -c "import fresnel; print(fresnel)"
        env:
          PYTHONPATH: ${{ github.workspace }}/install
      - name: Run tests
        run: python3 -m pytest --pyargs fresnel -v --log-level=DEBUG --durations=0
        env:
          PYTHONPATH: ${{ github.workspace }}/install
      - name: Render gallery images
        if: matrix.render_gallery
        run: for i in *.py; do echo "Rendering $i" && python3 $i || exit 1; done
        working-directory: code/doc/gallery
        env:
          PYTHONPATH: ${{ github.workspace }}/install

  # unit_test_other:
  #   name: Unit test on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-10.15, windows-2019]

  #   steps:
  #     - uses: actions/checkout@v2.3.4
  #       with:
  #         path: code
  #     - name: Install prereqs
  #       run: python3 -m pip install -r code/.github/requirements-test.txt
  #     - name: Configure
  #       run: cmake -S code -B build
  #     - name: Build
  #       run: cmake --build build -j 4 --config Release
  #     - if: runner.os == 'Windows'
  #       name: Copy pyd files
  #       run: cp ./gsd/Release/*.pyd gsd/
  #       working-directory: build
  #     - name: Run tests
  #       run: python3 -m pytest --pyargs gsd ${pytest_options} -v --log-level=DEBUG
  #       env:
  #         PYTHONPATH: ${{ github.workspace }}/build

  # # This job is used to provide a single requirement for branch merge conditions.
  # tests_complete:
  #   name: Unit test
  #   if: always()
  #   needs: [unit_test_linux, unit_test_other]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: echo "Done!"
